Add dallas multisensor support
Aircoookie/WLED pull request #2406
Opened 2021-12-10 23:12 UTC by lobo0

Add possibility to use up to 8 dallas sensors at one pin in usermode - DALLASTEMPERATURE.
Sensors are automaticaly discovered. 
Also there is a possibility to send the information by mqtt and show information about temperature on info section .

2021-12-11 12:58 UTC, blazoncek commented
Thank you for this contribution. I was postponing fixing this usermod for too long and it looks like it paid off. 😀 
One question: Do you see occasional incorrect reading on ESP32 or does your code solve that issue?

I will pull this into my fork and test it then merge if everything is ok.

2021-12-11 16:38 UTC, lobo0 commented
I don't test it on esp32, but on esp8266 I can see occasional incorrect reading (85*C). 
I'll try not to send erroneous readings.

2021-12-11 20:23 UTC, blazoncek commented
Please do test on ESP32 as well since there are issues on it.

2021-12-11 21:24 UTC, lobo0 commented
Currently I don't have any ESP32, but I think it should work. Could anyone test this code on ESP32?

2021-12-11 23:28 UTC, Aircoookie commented
Does not appear to work for me on my in-field ESP32, `DS18X20Data.sensors` is 0.
Will test with another unit tomorrow, as my main unit may have a hardware issue with the temp sensor (it stopped working some time ago)

2021-12-14 16:01 UTC, blazoncek commented
Does not work for me as well on ESP32.
Using @srg74 Wemos shield (confirmed working prior to this change) with DS18B20 at GPIO23.

2021-12-14 16:21 UTC, blazoncek requested changes
Does not work on ESP32 since it cannot find a sensor.

2021-12-14 16:21 UTC, blazoncek commented on usermods/Temperature/usermod_temperature.h
> +  char name[17];
Why name? Waste of RAM.

2021-12-14 16:21 UTC, blazoncek commented on usermods/Temperature/usermod_temperature.h
> +} ds18x20_sensor[DS18X20_MAX_SENSORS];
Why not dynamically allocate from heap as much as there are sensors?

2021-12-14 16:21 UTC, blazoncek commented on usermods/Temperature/usermod_temperature.h
> +      for (uint32_t i = 0; i < num_sensors; i++) {
Is this necessary? Why swapping?

2021-12-14 16:21 UTC, blazoncek commented on usermods/Temperature/usermod_temperature.h
> +    void Ds18x20Search(void) {
ESP32 may have timing issues with OneWire. Check this routine thoroughly on ESP32 with short and long (3-5m) wires on sensors.

2021-12-17 20:16 UTC, blazoncek commented
Any updates? I was not able to make it work on ESP32.

2021-12-20 21:35 UTC, lobo0 commented
I am waiting for ESP32 (it's on the way), so I need more time to test it.

2022-07-25 07:22 UTC, blazoncek commented
Closing as there has been no progress since December and code has progressed beyond simple resolving conflicts.

2022-07-25 07:22 UTC, closed without merging