Fix ledmap dropdown in presets
Aircoookie/WLED pull request #2885
Opened 2022-11-15 12:06 UTC by ewoudwijma

The ledmap drop down in presets is currently not working, it should show the ledmap included in the api and if dropdown is updated, the api should also be updated. And if set to non should be removed.
Also when set to none, the customMappingTable should be cleared.

Removed also the 0 as non functional dropdown option, and shows ledmapx.json instead of only x.

Note: json files should be named ledmap1.json until ledmap9.json. Ledmap0.json will not be read but is used as "no ledmap". 

This is fixed in this pull request

2022-11-16 06:13 UTC, blazoncek requested changes
I have not recently tested ledmap loading so I cannot comment if some other change in the code broke functionality. Will do, once I get the time.

The changes proposed work against original desire of ledamp 0 clearing current ledmap (as `ledmap.json` is used as a default ledmap (loaded at boot) if present). This is due to legacy reasons (there is no `ledmap0.json`).

I cannot approve current implementation as I see it flawed.

2022-11-16 06:13 UTC, blazoncek commented on wled00/presets.cpp
> +  loadLedmap = sObj["ledmap"];
IMO this is taken care of in line 373 of json.cpp.

2022-11-16 06:13 UTC, blazoncek commented on wled00/util.cpp
> +  ledMaps = 0;
As stated above, ledmap 0 always *exists*. If there is no file "ledmap.json" it means no ledmap is used, use default (ever increasing) LED order (AKA clear current ledmap).

2022-11-16 14:35 UTC, blazoncek commented
I have tested ledmap loading (from presets) in current main (0.14, build 2211130) and it works as expected/designed.
No changes are necessary.

2022-11-16 18:29 UTC, blazoncek commented
> Next from the comments you made in the code which I will follow up I still think the ui is not intuitive, so I will update this pr, up to you to accept or reject then.
> 
> Don't you think it's a bug that the drop-down is not updated in the api?

No need to do UI changes as I am adding clarification to that and also a possibility to change ledmap on its own without saving it in preset 1st.
No, I do not think it is a bug. There is no need for that information in UI.
![Screenshot 2022-11-16 at 19 26 02](https://user-images.githubusercontent.com/7722392/202262942-63228fbd-680f-4860-8605-96c3fab226b2.png)
![Screenshot 2022-11-16 at 19 26 15](https://user-images.githubusercontent.com/7722392/202262946-180b39d7-5e7d-4dce-abb7-622c1c3c244f.png)

2022-11-16 19:08 UTC, MoonModules commented
Cool, let me know when it is ready.
Will you also update https://kno.wled.ge/advanced/mapping/ to describe the dropdown as I still do not understand why you can update that dropdown if nothing happens, hopefully that is part of your fix

2022-11-16 21:15 UTC, MoonModules commented
> I have tested ledmap loading (from presets) in current main (0.14, build 2211130) and it works as expected/designed.
> No changes are necessary.

Haha, no changes necessary but you copied half of my proposed changes ;-)

2022-11-17 05:19 UTC, blazoncek commented
Just to make you happy. 😜

2022-11-17 05:19 UTC, closed without merging

2022-11-17 10:01 UTC, MoonModules commented
Using ledmapsX.json in the dropdown instead of only X ;-)