2d mapping 2
Aircoookie/WLED pull request #2892
Opened 2022-11-20 00:17 UTC by ctjet

This enables WLED in 2D mode to support gaps and offsets of panels in the matrix. Panels may now be spaced and ordered however the user sees fit.

![Screenshot 2022-11-19 175952](https://user-images.githubusercontent.com/8173807/202876282-e20de0e4-a232-4c87-86ce-83567c106276.png)

### Changes

wled00/cfg.cpp
- No longer store matrix dimensions in panels, instead, store the total count of panels
- Store an X and Y offset in pixels from top left of matrix for each panel. (uint8_t)

wled00/FX_2Dfcn.cpp
- No longer calculate matrix serpentine, bottom, right, and vertical. This functionality is now in 2D settings webpage. Instead use already set panel offsets and just calculate pixel offsets per panel relative to that.

wled00/data/settings_2D.htm
- Add "matrix generator" field. Use this field to populate the panels array and new "Number of panels" field with the correct values for a new matrix.
- Add offsets for each panel from the top left of the matrix. These can be manually tweaked to allow for gaps and weird spacings.

Other supporting changes were made for above functionality.

### Notes
I am by no means a Javascript or Web developer. All of the JS and HTML, as well as my layout of the page, should be checked and potentially tweaked.

This should not be merged until it is decided how to handle custom maps with gaps. This functionality currently can balloon the size of the Custom Map array as every unused pixel takes up 2 bytes. This is a problem especially for ESP8266.

I am not sure if this breaks the config when upgrading to this version due to the config changes. Must be tested.

2022-11-20 07:36 UTC, blazoncek commented
Looks slick.

2022-11-22 07:29 UTC, blazoncek commented
Each iteration looks better. 👏 
Adding unequal panel support may be your next step and then it will be almost perfect.

2022-11-22 19:23 UTC, ctjet commented
Added per panel w/h, still looking into a fix for a few bugs

2022-12-01 09:44 UTC, blazoncek commented on wled00/FX.h
> +      unsigned int xOffset  : 8; // x offset relative to the top left of matrix in LEDs
You may want to move these four variables out of bitfield to allow lower CPU overhead.

2022-12-18 18:48 UTC, blazoncek commented
@ctjet can you, please, pull recent commits and resolve conflicts?

2022-12-23 11:52 UTC, ctjet commented
@blazoncek should be updated, do I need to do anything special for 0.14?

2022-12-23 15:16 UTC, blazoncek commented
> do I need to do anything special for 0.14?

No. It just needs to be in line with recent main.

2023-01-01 10:24 UTC, blazoncek requested changes
There were some changes upstream that require you to update your code. It may not work properly otherwise.

I am also wondering why did you include `html_simple.h` as its source didn't change.

2023-01-01 10:24 UTC, blazoncek commented on wled00/FX.h
> +      matrixWidth(DEFAULT_LED_COUNT),
This set-up is not 2D, please change it that both dimensions are >1.

2023-01-01 10:24 UTC, blazoncek commented on wled00/FX.h
> +      matrixWidth,
These two are no longer part of `strip`.

2023-01-01 10:24 UTC, blazoncek commented on wled00/FX.h
> +      unsigned int xOffset  : 8; // x offset relative to the top left of matrix in LEDs
I am still waiting for these 4 to get removed from bitfield.

2023-01-01 10:24 UTC, blazoncek commented on wled00/FX_2Dfcn.cpp
> +    matrixWidth = 0;
You will need to revert to `Segment::maxWidth` and `Segment::maxHeight`.

Do similar for the code below.

2023-01-01 14:46 UTC, blazoncek commented
Maybe it is not ready after all.
@ctjet how do you plan to arrange panels? Always by entering x and y offsets?
That is awkward IMO.

2023-01-01 18:55 UTC, blazoncek commented
Got it working now.
I'm still not sure entering offsets is a good UX.
It might be better to add graphical UI at some point, but that is beyond my skills.

2023-01-02 11:05 UTC, Aircoookie approved these changes

2023-01-02 11:17 UTC, blazoncek approved these changes

2023-01-02 11:17 UTC, blazoncek commented on wled00/FX.h
> +      unsigned int xOffset  : 8; // x offset relative to the top left of matrix in LEDs
Did it myself.

2023-01-02 17:19 UTC, blazoncek commented
@softhack007 are you ok to merge this?

2023-01-02 17:38 UTC, softhack007 approved these changes
@blazoncek just did a quick code review, however 2D is not really my field ...
I think its good to merge 👍

2023-01-02 19:56 UTC, merged