ESP32C3 stable.
Aircoookie/WLED pull request #2958
Opened 2022-12-16 19:19 UTC by abhishek2desh

ESP32-C3-Devkit stable.

2022-12-16 20:09 UTC, blazoncek commented
Why? I have C3 and it is running stable with current set-up.
I would prefer not to use external platforms if not necessary.

Other than that, making unnecessary changes in platformio.ini is not welcome.

2022-12-16 20:13 UTC, blazoncek requested changes
If you want custom build environment use `platformio_override.ini` and do not change upstream platformio.ini.

2022-12-16 20:13 UTC, blazoncek commented on platformio.ini
> +# default_envs = nodemcuv2, esp8266_2m, esp01_1m_full, esp32dev, esp32_eth, esp32s2_saola, esp32c3, esp32s3dev_8MB
Don't change that.

2022-12-16 20:13 UTC, blazoncek commented on platformio.ini
> +platform = https://github.com/tasmota/platform-espressif32/releases/download/v2.0.3rc1/platform-espressif32-2.0.3new.zip
Why not stock? Where is the issue with stock platform?

2022-12-16 20:13 UTC, blazoncek commented on platformio.ini
> +  -D LEDPIN=2
Not needed.

2022-12-16 21:14 UTC, softhack007 commented
Sorry but I will not approve this PR as it is today. 
Reasons as explained by @blazoncek.

2022-12-16 23:11 UTC, abhishek2desh commented
I tried using current setup but there were some issues with littlefs
library and the board kept rebooting indefinitely. So I made the change to
ini file.

On Fri, Dec 16, 2022, 3:09 p.m. Blaž Kristan ***@***.***>
wrote:

> Why? I have C3 and it is running stable with current set-up.
> I would prefer not to use external platforms if not necessary.
>
> Other than that, making unnecessary changes in platformio.ini is not
> welcome.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Aircoookie/WLED/pull/2958#issuecomment-1355531484>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACD6Q7HZEFOTWNSPHXKFWYLWNTEAJANCNFSM6AAAAAATBM3QGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-12-17 00:05 UTC, Aircoookie commented
I would support adding the tasmota-compiled platform as a commented out option. The other changes to platformio will not get merged.

2022-12-17 13:56 UTC, softhack007 commented
Thanks @Aircoookie this solution seems to be a good compromise.

2023-01-16 21:05 UTC, softhack007 commented
I have been playing around with a -C3 recently, and also saw issues with corrupted littlefs, that happen with espressif@5.1.1 in combination with ARDUINO_USB_CDC_ON_BOOT=0. These problems disappear when using espressif@5.2.0. Espressif@5.1.1 seems to work when ARDUINO_USB_CDC_ON_BOOT=1. So my proposal is to try with espressif@5.2.0.

@abhishek2desh can you explain a bit more why you picked `platform=https://github.com/tasmota/platform-espressif32/releases/download/v2.0.3rc1/platform-espressif32-2.0.3new.zip` ? It seems to be a pre-release from tasmota, based on arduino-esp32 v2.0.3 in "tasmota flavour". What makes this one special?

2023-01-16 21:15 UTC, blazoncek commented
@softhack007 indeed ARDUINO_USB_CDC_ON_BOOT caused many issues as well with S2 when I was testing it (corrupting LittleFS and/or rebooting/panicking).

2023-01-16 21:22 UTC, softhack007 commented
A few users have confirmed already that littlefs corruption on -C3 is resolved by using `platform=espressif@5.2.0`. So I prefer to have this as an optional line in platformio.ini, instead of an older tasmota pre-release version.

Closing this PR, in favour of commit https://github.com/Aircoookie/WLED/commit/b8cc78358367befc134f133738e2e58157ee92dd

2023-01-16 21:22 UTC, closed without merging

2023-01-28 16:28 UTC, Paras-PC commented
> Why? I have C3 and it is running stable with current set-up. I would prefer not to use external platforms if not necessary.
> 
> Other than that, making unnecessary changes in platformio.ini is not welcome.

Which file did you flash on your ESP-C3?
I want to flash a Seeed Studio XIAO ESP32C3

2023-01-28 20:20 UTC, blazoncek commented
> Which file did you flash on your ESP-C3? I want to flash a Seeed Studio XIAO ESP32C3

My own compile from PIO.
Env posted on Discord.