Add WireGuard VPN usermod
Aircoookie/WLED pull request #3270
Opened 2023-06-25 05:00 UTC by acvigue

Adds a WireGuard usermod for ESP32 that allows WLED devices to join a remote network in situations where wireless isolation prevents local control.

2023-07-03 02:29 UTC, acvigue commented
Is there any chance someone could take a quick look at this?

Thank you all!

2023-07-03 04:20 UTC, blazoncek requested changes
I have no way of testing it so I trust it works for you.
There are some things I'd like you to address before merging, though.

2023-07-03 04:20 UTC, blazoncek commented on usermods/wireguard/wireguard.h
> +        top[F("Endpoint Address")] = endpoint_address;
Please avoid key names with spaces and make them short if possible.
You can use utility function `addInfo()` to make UI better.

2023-07-03 04:20 UTC, blazoncek commented on usermods/wireguard/wireguard.h
> +    String preshared_key;  // [Interface] PrivateKey
Why `String`? You are not doing much processing on strings so it may be more efficient to use `char[]` or `char*`.

2023-07-03 04:20 UTC, blazoncek commented on usermods/wireguard/wireguard.h
> +            wg.begin(local_ip, private_key.c_str(), endpoint_address.c_str(), public_key.c_str(), endpoint_port, NULL);
I am not sure if this belongs to `loop()`. Perhaps a better place may be `connected()`?
`loop()` is executed at full possible rate which may be up to 5000-6000 times per second.

2023-07-03 04:49 UTC, blazoncek commented
One more thing: Please add your contact info into readme.md for user reference in case someone needs help with usermod.

2023-07-21 23:08 UTC, acvigue commented
Can you look at the changes I made?

2023-07-22 08:00 UTC, blazoncek commented
Using char[xx] eats a lot of stack, which is limited on MCU.
It may interfere with WLED behaviour (which itself uses a lot of stack space on some occasions) so it would be better to use `new` or `malloc()` for all the strings you want to store in `setup()` or `readFromConfig()`.

Otherwise I see you updated as requested and see no objection to this usermod.

2023-07-24 18:08 UTC, acvigue commented
fixed

2023-07-24 20:17 UTC, blazoncek commented
Are you sure this works?
`setup()` is called *after* `readFromConfig()`. So `malloc()` happens *after* all `strncpy()` which is not good.

I may have unintentionally mislead you when I suggested `setup()`. Constructor would be a better place, and then `free()` in destructor. Sorry about that.

2023-07-25 00:49 UTC, acvigue commented
>  So malloc() happens after all strncpy() which is not good.

Oops, ok. I'll take a look at fixing it tomorrow.

2023-07-26 14:28 UTC, Aircoookie commented
Hmm, correct me if I'm wrong, but since these keys are private members, they are created on the heap anyways as the usermod constructor is called in `usermods_list.cpp`. Stack would only be used if they are local variables in a given function.
Sorry that I'm only taking a look at it now, but to me this seems fine as implemented in 7296e87d2f82504e498dc4ed6204669f0799a1dd ...
Either way as this is an ESP32-only mod, memory usage is far less of a concern than with mods intended for ESP8266 as well.

2023-07-26 17:26 UTC, acvigue commented
> Sorry that I'm only taking a look at it now, but to me this seems fine as implemented in https://github.com/Aircoookie/WLED/commit/7296e87d2f82504e498dc4ed6204669f0799a1dd ...
Either way as this is an ESP32-only mod, memory usage is far less of a concern than with mods intended for ESP8266 as well.

All good, thanks for the input. I went ahead and reverted my branch back to that commit and then merged in all the changes from `main` so it should be good to go.

2023-07-26 20:28 UTC, blazoncek commented
> they are created on the heap anyways

You are correct and I was wrong. _Mea culpa._

2023-07-27 09:17 UTC, Aircoookie commented
All good :) I'd say this is ready to merge!

2023-07-27 09:35 UTC, merged