Inline iro.js and rangetouch.js
Aircoookie/WLED pull request #3597
Opened 2023-12-19 20:28 UTC by WoodyLetsCode

Since #3511 has been merged, we can now include `iro.js` and `rangetouch.js` using the inliner again.

I also removed the unused feedback function as it was probably forgotten to remove in commit d6c0642a02ab2c43391ebb7db3ef353f21cbe5fb.

2023-12-19 20:38 UTC, blazoncek requested changes
Generally approved from my side.
Removal of iro.js and rangetouch.js was needed for simplified UI.

You may want to edit cdata.json to comment out generation of .htm files and remove/comment references from wled_server.cpp for PR to be complete.

2023-12-19 20:38 UTC, blazoncek commented on wled00/data/index.htm
> -	<script>
I would keep this for future reference as a comment.

2023-12-19 21:51 UTC, WoodyLetsCode commented on wled00/data/index.htm
> -	<script>
I see no advantage in keeping that as a comment. If you want to look at the code again in the future, you can simply look at the Git history.
I think that would just make the code less readable and most people would probably wonder what this comment is for when they see it.

And what exactly would you want to leave as a comment? The complete `<script>` block or just the feedback function?

2023-12-20 08:46 UTC, blazoncek commented on wled00/data/index.htm
> -	<script>
History is one thing, actual snippet embedded as a comment is another. Snippet can be used immediately by anyone while code from history is only viable option for those that know it was there. Snippet (as a comment) *does not reduce readability* of the code, even without any actual comment in it, on the contrary IMO it adds value for a possible future when such feature may be re-implemented.

Dynamically loading of JS files may come in handy in the future (for possible extensions) and at least POC code should be kept in place as a guideline for such case. Commented code does not increase binary code size or adds performance penalties.

I am in favour of reducing HTTP requests to ESP but not at the expense of removing *knowledge* from source files. Otherwise you can strip *every* comment from *all* source files.

2023-12-20 10:42 UTC, WoodyLetsCode commented on wled00/data/index.htm
> -	<script>
I added a comment with referencte to how it was done in 0.14.0. What do you think of this?
I think this is better because we don't have this big block of commented out code (so the code looks cleaner) and we still preserve the knowledge.

2023-12-21 19:42 UTC, blazoncek approved these changes

2023-12-21 19:43 UTC, merged