Add SSD1309_64 I2C Support for FLD Usermod
Aircoookie/WLED pull request #3836
Opened 2024-03-19 21:09 UTC by THATDONFC

Adds support for SSD1309_64 I2C display to the FLD Usermod.

Fixes an issue where palettes with an ID > 58 but not a custom palette did not display the palette name on the display.

There are quite a bit of whitespace diffs caused by trailing spaces being removed before commit.

2024-03-20 07:06 UTC, blazoncek requested changes
I would avoid breaking changes if possible. Even at the expense of awkward UI order if necessary (but I think it will be ok).

2024-03-20 18:08 UTC, THATDONFC commented
> I would avoid breaking changes if possible. Even at the expense of awkward UI order if necessary (but I think it will be ok).

Got it. So move the new display to the end of the list and make it #9 and change the existing ones back to their original values?

My OCD is going to hate that but I understand wanting to avoid breaking changes wherever possible.

2024-03-20 18:21 UTC, blazoncek commented
Yes. Thank you.
And I completely understand your feelings as well.

2024-03-20 20:50 UTC, THATDONFC commented
This should revert the breaking change. Let me know if you want me to move the new display to the end of the list in each place I added it. I think this is a good compromise to keep the UI order organized while retaining backwards compatibility.

2024-03-21 04:44 UTC, blazoncek approved these changes

2024-03-21 04:48 UTC, merged